name: Deploy Azure Function

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - test

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ${{ vars.AZURE_FUNCTIONAPP_PACKAGE_PATH || '.' }}
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION || 3.11 }}
  ENVIRONMENT: ${{ inputs.environment || 'test' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ env.ENVIRONMENT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Environment
        run: echo "Deploying on ${{ env.ENVIRONMENT }} environment"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

#         Config for flex consumption
          sku: flexconsumption
          remote-build: true
