name: Deploy Azure Function

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Deploy Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.APP_FUNCTION_NAME }}
          package: .

      - name: Logout from Azure
        run: az logout
